services:
    app:
        build:
            context: docker
            dockerfile: Dockerfile
        image: laravel-app
        container_name: content-app
        volumes:
            - .:/var/www
        depends_on:
            - db
        networks:
            - content

    db:
        image: postgres:15
        container_name: content-db
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5436:${DB_PORT}"
        volumes:
            - content:/var/lib/postgresql/data
        networks:
            - content

    nginx:
        image: nginx:alpine
        container_name: content-nginx
        ports:
            - "88:80"
        volumes:
            - .:/var/www
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - content



volumes:
    content:

networks:
    content:
