name: Imtihon Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup SSH
        run : |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600~/.ssh/id_rsa
          echo -e "HOST *\n\tStrictHostKeyChecking no\n" >> ~/ssh/config

      - name: Deploy via SSH
        run: |

